<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var array $query
 */

$translate = $this->plugin('translate');
?>

<?php
$element = new \Laminas\Form\Element\Radio('has_original');
$element
    ->setLabel('Presence of original file') // @translate
    ->setValueOptions([
        '1' => 'Has original file', // @translate
        '0' => 'Has no original file', // @translate
        '' => 'Any', // @translate
    ])
    ->setValue($query['has_original'] ?? '')
    ->setAttributes([
        'id' => 'has_original',
        'class' => 'query-has-original',
        'value' => $query['has_original'] ?? '',
        'aria-label' => $translate('Search by presence of original file'), // @translate
    ]);
echo $this->formRow($element);
