<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var array $query
 */

$translate = $this->plugin('translate');
?>

<div id="hasthumbnails-queries" class="field" role="group" aria-labelledby="by-has-thumbnails-label">
    <div class="field-meta">
        <span id="by-has-thumbnails-label" class="label"><?= $translate('Has thumbnails') ?></span>
    </div>
    <div class="inputs">
        <div class="value">
            <?php
            $select = (new \Laminas\Form\Element\Radio())
                ->setName('has_thumbnails')
                ->setValueOptions([
                    '1' => 'Yes', // @translate
                    '0' => 'No', // @translate
                    '' => 'Any', // @translate
                ])
                ->setAttributes([
                    'class' => 'query-has-thumbnails',
                    'value' => $query['has_thumbnails'] ?? '',
                    'aria-label' => $translate('Has thumbnails'), // @translate
                ]);
            echo $this->formRadio($select);
            ?>
        </div>
    </div>
</div>
