<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var array $query
 *
 * Same as core template, with:
 * - include resource "without item set" (id = 0);
 * - use chosen-select;
 * - short echo.
 */

$plugins = $this->getHelperPluginManager();
$status = $plugins->get('status');
$translate = $plugins->get('translate');
$hyperlink = $plugins->get('hyperlink');
$itemSetSelect = $plugins->get('itemSetSelect');

// Prepare the item set queries
$ids = $query['item_set_id'] ?? [];
if (!is_array($ids)) {
    $ids = [$ids];
}
$ids = array_filter($ids, 'is_numeric') ?: [null];

if ($status->isSiteRequest()) {
    $layout = $plugins->get('layout');
    $site = $layout->site;
    if (!$site || !$site->siteItemSets()) {
        return;
    }
    $filterLocale = (bool) $this->siteSetting('filter_locale_values');
    $lang = $this->lang();

    $selectOptions = [
        'disable_group_by_owner' => true,
        'query' => ['site_id' => $site->id()],
        'lang' => ($filterLocale == 1 ? $lang : null),
        'prepend_value_options' => [
            '0' => '[none]',
        ],
    ];
} else {
    $selectOptions = [
        'prepend_value_options' => [
            '0' => '[none]',
        ],
    ];
}
?>

<div id="item-sets" class="field removable multi-value" role="group">
    <div class="field-meta">
        <span id="by-item-set-label" class="label"><?= $translate('Search by item set') ?></span>
        <?= $hyperlink('', '#', ['class' => 'expand', 'title' => $translate('Expand')]) ?>
        <div class="collapsible">
            <div class="field-description"><?= $translate('Searches for items that are assigned to any of these item sets.') ?></div>
        </div>
        <button type="button" class="add-value o-icon-add button" aria-label="<?= $translate('Add new item set') ?>" title="<?= $translate('Add new item set') ?>"></button>
    </div>
    <div class="inputs">
        <?php foreach ($ids as $id): ?>
        <div class="value">
            <?= $itemSetSelect([
                'name' => 'item_set_id[]',
                'options' => $selectOptions,
                'attributes' => [
                    'value' => $id,
                    'aria-labelledby' => 'by-item-set-label',
                    'class' => 'chosen-select',
                ],
            ]) ?>
            <button type="button" class="o-icon-delete remove-value button" aria-label="<?= $translate('Remove value') ?>" title="<?= $translate('Remove value') ?>"></button>
        </div>
        <?php endforeach; ?>
    </div>
</div>
