<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var array $query
 */

$translate = $this->plugin('translate');
?>

<div id="mediatype-queries" class="field" role="group" aria-labelledby="by-media-type-label">
    <div class="field-meta">
        <span id="by-media-type-label" class="label"><?= $translate('Media type') ?></span>
    </div>
    <div class="inputs">
        <div class="value">
            <?= $this->mediaTypeSelect([
                'name' => 'media_types',
                'options' => [
                    'label' => 'Search by media type', // @translate
                    'empty_option' => '',
                ],
                'attributes' => [
                    'id' => 'media-type',
                    'value' => empty($query['media_types']) ? [] : (array) $query['media_types'],
                    'class' => 'chosen-select query-mediatype',
                    'multiple' => true,
                    'aria-labelledby' => 'by-media-type-label',
                    'data-placeholder' => 'Select media types…', // @translate
                ],
            ]) ?>
        </div>
    </div>
</div>
