<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var array $query
 *
 *
 * Same as core template, with:
 * - use option to restrict to used terms in admin;
 * - more querier options;
 * - use chosen-select;
 * - short echo.
 */

$plugins = $this->getHelperPluginManager();
$status = $plugins->get('status');
$setting = $plugins->get('setting');
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');
$siteSetting = $plugins->get('siteSetting');
$propertySelect = $plugins->get('propertySelect');

$isSiteRequest = $status->isSiteRequest();
$applyTemplates = $isSiteRequest ? $siteSetting('advancedsearch_apply_templates') : false;
$usedTerms = $isSiteRequest ? $siteSetting('advancedsearch_restrict_used_terms', true) : $setting('advancedsearch_restrict_used_terms', true);

// Prepare the property queries.
$properties = $query['property'] ?? [];
$properties = array_filter($properties, function ($value) {
    return isset($value['text']) ? '' !== trim($value['text']) : true;
});
if (!$properties) {
    $properties[] = [];
}

if (isset($query['search'])) {
    unset($properties[0]['joiner']);
    array_unshift($properties, [
        'property' => '',
        'type' => 'in',
        'text' => $query['search'],
    ]);
}

$queryOption = function ($value, array $search, $key, $text) {
    $selected = null;
    if (isset($search[$key]) && $value === $search[$key]) {
        $selected = ' selected';
    }
    return sprintf('<option value="%s"%s>%s</option>', $value, $selected, $text);
};
$queryText = function (array $search, $index) use ($escape, $translate) {
    $text = $search['text'] ?? null;
    return sprintf('<input type="text" class="query-text" name="%s" value="%s" aria-label="%s">',
        $escape("property[$index][text]"),
        $escape($text),
        $escape($translate('Query text')));
};
?>

<div id="property-queries" class="field removable multi-value" role="group" aria-labelledby="by-value-label">
    <div class="field-meta">
        <span id="by-value-label" class="label"><?= $translate('Search by value') ?></span>
        <button type="button" class="add-value o-icon-add button" aria-label="<?= $translate('Add new value') ?>" title="<?= $translate('Add new value') ?>"></button>
    </div>
    <div class="inputs">
        <?php
        $index = 0;
        foreach ($properties as $property):
            $stem = "property[$index]";
            $propertyList = isset($property['property'])
                ? (is_array($property['property']) ? $property['property'] : [$property['property']])
                : [null];
        ?>
        <div class="value">
            <select class="joiner chosen-select" name="<?= $escape($stem . '[joiner]') ?>">
                <?= $queryOption('and', $property, 'joiner', $translate('AND')) ?>
                <?= $queryOption('or', $property, 'joiner', $translate('OR')) ?>
            </select>
            <?= $propertySelect([
                'name' => $stem . '[property]',
                'options' => [
                    'empty_option' => '[Any Property]', // @translate
                    'apply_templates' => $applyTemplates,
                    'used_terms' => $usedTerms,
                ],
                'attributes' => [
                    'class' => 'query-property chosen-select',
                    'value' => $propertyList,
                    'aria-label' => $translate('Property'),
                    'multiple' => true,
                    'data-placeholder' => $translate('Select properties…'),
                ],
            ]) ?>
            <select class="query-type chosen-select" name="<?= $escape($stem . '[type]') ?>" aria-label="<?= $translate('Query type') ?>">
                <?= $queryOption('eq', $property, 'type', $translate('is exactly')) ?>
                <?= $queryOption('neq', $property, 'type', $translate('is not exactly')) ?>
                <?= $queryOption('in', $property, 'type', $translate('contains')) ?>
                <?= $queryOption('nin', $property, 'type', $translate('does not contain')) ?>
                <?= $queryOption('sw', $property, 'type', $translate('starts with')) ?>
                <?= $queryOption('nsw', $property, 'type', $translate('does not start with')) ?>
                <?= $queryOption('ew', $property, 'type', $translate('ends with')) ?>
                <?= $queryOption('new', $property, 'type', $translate('does not end with')) ?>
                <?= $queryOption('res', $property, 'type', $translate('is resource with ID')) ?>
                <?= $queryOption('nres', $property, 'type', $translate('is not resource with ID')) ?>
                <?= $queryOption('ex', $property, 'type', $translate('has any value')) ?>
                <?= $queryOption('nex', $property, 'type', $translate('has no values')) ?>
                <?= $queryOption('exs', $property, 'type', $translate('has a single value')) ?>
                <?= $queryOption('nexs', $property, 'type', $translate('has not a single value')) ?>
                <?= $queryOption('exm', $property, 'type', $translate('has multiple values')) ?>
                <?= $queryOption('nexm', $property, 'type', $translate('has not multiple values')) ?>
                <?= $queryOption('lex', $property, 'type', $translate('is a linked resource')) ?>
                <?= $queryOption('nlex', $property, 'type', $translate('is not a linked resource')) ?>
                <?= $queryOption('lres', $property, 'type', $translate('is linked with resource with ID')) ?>
                <?= $queryOption('nlres', $property, 'type', $translate('is not linked with resource with ID')) ?>
                <?php /* // TODO Require a js to force value to be "literal", "resource" or "uri". ?>
                <?= $queryOption('tp', $property, 'type', $translate('has main type')) ?>
                <?= $queryOption('ntp', $property, 'type', $translate('has not main type')) ?>
                <?php */ ?>
                <?= $queryOption('tpl', $property, 'type', $translate('has type literal-like')) ?>
                <?= $queryOption('ntpl', $property, 'type', $translate('has not type literal-like')) ?>
                <?= $queryOption('tpr', $property, 'type', $translate('has type resource-like')) ?>
                <?= $queryOption('ntpr', $property, 'type', $translate('has not type resource-like')) ?>
                <?= $queryOption('tplu', $property, 'type', $translate('has type uri-like')) ?>
                <?= $queryOption('ntpu', $property, 'type', $translate('has not type uri-like')) ?>
                <?= $queryOption('dtp', $property, 'type', $translate('has data type')) ?>
                <?= $queryOption('ndtp', $property, 'type', $translate('has not data type')) ?>
            </select>
            <?= $queryText($property, $index) ?>
            <button type="button" class="o-icon-delete remove-value button" aria-label="<?= $translate('Remove value') ?>" title="<?= $translate('Remove value') ?>"></button>
        </div>
        <?php
            ++$index;
        endforeach;
        ?>
    </div>
</div>
