<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var array $query
 *
 * Same as core template, with:
 * - include resource "without template" (id = 0);
 * - use chosen-select;
 * - short echo.
 */

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');
$hyperlink = $plugins->get('hyperlink');
$resourceTemplateSelect = $plugins->get('resourceTemplateSelect');

// Prepare the resource template query.
$ids = $query['resource_template_id'] ?? [];
if (!is_array($ids)) {
    $ids = [$ids];
}
$ids = array_filter($ids, 'is_numeric') ?: [null];
?>

<div id="resource-templates" class="field removable multi-value" role="group">
    <div class="field-meta">
        <span id="by-resource-template-label" class="label"><?= $translate('Search by template') ?></span>
        <?= $hyperlink('', '#', ['class' => 'expand', 'title' => $translate('Expand')]) ?>
        <div class="collapsible">
            <div class="field-description"><?= $translate('Searches for resources that use any of these templates.') ?></div>
        </div>
        <button type="button" class="add-value o-icon-add button" aria-label="<?= $translate('Add new template') ?>" title="<?= $translate('Add new template') ?>"></button>
    </div>
    <div class="inputs">
        <?php foreach ($ids as $id): ?>
        <div class="value">
            <?= $resourceTemplateSelect([
                'name' => 'resource_template_id[]',
                'options' => [
                    'prepend_value_options' => [
                        '0' => '[none]',
                    ],
                ],
                'attributes' => [
                    'value' => $id,
                    'aria-labelledby' => 'by-resource-template-label',
                    'class' => 'chosen-select',
                ],
            ]) ?>
            <button type="button" class="o-icon-delete remove-value button" aria-label="<?= $translate('Remove value') ?>" title="<?= $translate('Remove value') ?>"></button>
        </div>
        <?php endforeach; ?>
    </div>
</div>
