<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var array $query
 *
 * Same as core template, with:
 * - option used term for admin;
 * - include resource "without class" (id = 0);
 * - use chosen-select;
 * - short echo.
 */

$plugins = $this->getHelperPluginManager();
$status = $plugins->get('status');
$translate = $plugins->get('translate');
$hyperlink = $plugins->get('hyperlink');
$siteSetting = $plugins->get('siteSetting');
$resourceClassSelect = $plugins->get('resourceClassSelect');

$isSiteRequest = $status->isSiteRequest();
$applyTemplates = $isSiteRequest ? $siteSetting('search_apply_templates') : false;
$usedTerms = !$isSiteRequest;

// Prepare the resource class query.
$ids = $query['resource_class_id'] ?? [];
if (!is_array($ids)) {
    $ids = [$ids];
}
$ids = array_filter($ids) ?: [null];
$optionsQuery = [];
if ($isSiteRequest) {
    if ($siteSetting('vocabulary_scope') === 'sitewide') {
        $optionsQuery['site_id'] = $this->layout()->site->id();
    } elseif ($siteSetting('vocabulary_scope') === 'cross-site') {
        $optionsQuery['used'] = true;
    }
}
?>

<div id="resource-class" class="field removable multi-value" role="group">
    <div class="field-meta">
        <span id="by-resource-class-label" class="label"><?= $translate('Search by class') ?></span>
        <?= $hyperlink('', '#', ['class' => 'expand', 'title' => $translate('Expand')]) ?>
        <div class="collapsible">
            <div class="field-description"><?= $translate('Searches for resources that are any of these classes.') ?></div>
        </div>
        <button type="button" class="add-value o-icon-add button" aria-label="<?= $translate('Add new class') ?>" title="<?= $translate('Add new class') ?>"></button>
    </div>
    <div class="inputs">
        <?php foreach ($ids as $id): ?>
        <div class="value">
            <?= $resourceClassSelect([
                'name' => 'resource_class_id[]',
                'attributes' => [
                    'value' => $id,
                    'aria-labelledby' => 'by-resource-class-label',
                    'class' => 'chosen-select',
                ],
                'options' => [
                    'prepend_value_options' => [
                        '0' => '[none]',
                    ],
                    'apply_templates' => $applyTemplates,
                    'used_terms' => $usedTerms,
                    'query' => $optionsQuery,
                ],
            ]) ?>
            <button type="button" class="o-icon-delete remove-value button" aria-label="<?= $translate('Remove value') ?>" title="<?= $translate('Remove value') ?>"></button>
        </div>
        <?php endforeach; ?>
    </div>
</div>
