<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var array $filters
 */

if (!count($filters)) return;

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$escapeAttr = $this->plugin('escapeHtmlAttr');
?>

<div class="search-filters">
    <?php foreach ($filters as $filterLabel => $filterValues): ?>
    <div class="filter">
        <span class="filter-label"><?= $escape($filterLabel) ?></span>
        <?php foreach ($filterValues as $urlQuery => $filterValue): ?>
        <a href="<?= $escapeAttr($urlQuery) ?>" class="filter-value"><?= $escape($filterValue) ?></a>
        <?php endforeach; ?>
    </div>
    <?php endforeach; ?>
</div>
