<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Omeka\Entity\User $user
 * @var array $links
 */

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');
$hyperlink = $plugins->get('hyperlink');
$urlHelper = $plugins->get('url');

$isGuest = !$this->userIsAllowed('Omeka\Controller\Admin\Index', 'index');
$hasGuest = $plugins->has('GuestWidget');

$this->headLink()
    ->prependStylesheet($this->assetUrl('css/user-bar.css', 'Omeka'))
    ->prependStylesheet('//fonts.googleapis.com/css?family=Source+Code+Pro|Lato:400,400italic,700,700italic');
?>

<div id="user-bar">
<?php if (isset($user)): ?>
    <div class="site-links">
    <?php foreach ($links as $link): ?>
        <span class="admin <?= $link['resource'] . ' ' . $link['action'] ?>">
            <?= $hyperlink($link['text'], $link['url']) ?>
        </span>
    <?php endforeach; ?>
    </div>

    <div class="user-links">
        <span class="user-id">
            <?php
            $url = $isGuest
                ? ($hasGuest ? $urlHelper('site/guest', ['site-slug' => $site->slug(), 'action' => 'me']) : '')
                : $urlHelper('admin/id', ['controller' => 'user', 'id' => $user->getId()]);
            echo sprintf($translate('Signed in as %s'), $url && ($hasGuest || !$isGuest) ? $hyperlink($user->getName(), $url) : $user->getName());
            ?>
        </span>
        <?php
        $url = $hasGuest ? $urlHelper('site/guest/guest', ['site-slug' => $site->slug(), 'action' => 'logout'], ['query' => $this->params()->fromQuery() ?: []], true) : $urlHelper('logout');
        echo $hyperlink($translate('Logout'), $url, ['class' => 'logout']);
        ?>
    </div>
<?php else: ?>
    <span class="login">
        <?php
        $url = $hasGuest
            ? $urlHelper('site/guest/anonymous', ['site-slug' => $site->slug(), 'action' => 'login'], ['query' => $this->params()->fromQuery() ?: []], true)
            : $urlHelper('login');
        echo $hyperlink($translate('Log in'), $url, ['class' => 'login']);
        ?>
    </span>
<?php endif; ?>
</div>
