<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \AdvancedSearch\Api\Representation\SearchConfigRepresentation $searchPage
 * @var bool $displayResults Skip form action?
 * @var \AdvancedSearch\Query $query
 * @var \AdvancedSearch\Response $response
 * @var string $heading
 */

$plugins = $this->getHelperPluginManager();
$escape = $this->plugin('escapeHtml');
$vars = $this->vars();
?>

<?php if (empty($displayResults) || empty($searchPage)): ?>

<div class="block-search">
    <?php if (!empty($heading)): ?>
    <h2><?= $escape($heading) ?></h2>
    <?php endif; ?>
    <?= $searchPage
        ? $this->searchForm($searchPage, null, $displayResults)
        : $this->searchingForm(null, $displayResults) ?>
</div>

<?php else: ?>

<?php if (!empty($heading)): ?>
<div class="block-search">
    <h2><?= $escape($heading) ?></h2>
</div>
<?php endif; ?>

<?php $vars->offsetUnset('displayResults') ?>
<?php $vars->offsetSet('skipFormAction', true) ?>
<?= $this->partial('search/search') ?>

<?php endif; ?>
