<?php

/*
 * Copyright BibLibre, 2016
 * Copyright Daniel Berthereau, 2018-2021
 *
 * This software is governed by the CeCILL license under French law and abiding
 * by the rules of distribution of free software.  You can use, modify and/ or
 * redistribute the software under the terms of the CeCILL license as circulated
 * by CEA, CNRS and INRIA at the following URL "http://www.cecill.info".
 *
 * As a counterpart to the access to the source code and rights to copy, modify
 * and redistribute granted by the license, users are provided only with a
 * limited warranty and the software's author, the holder of the economic
 * rights, and the successive licensors have only limited liability.
 *
 * In this respect, the user's attention is drawn to the risks associated with
 * loading, using, modifying and/or developing or reproducing the software by
 * the user in light of its specific status of free software, that may mean that
 * it is complicated to manipulate, and that also therefore means that it is
 * reserved for developers and experienced professionals having in-depth
 * computer knowledge. Users are therefore encouraged to load and test the
 * software's suitability as regards their requirements in conditions enabling
 * the security of their systems and/or data to be ensured and, more generally,
 * to use and operate it in the same conditions as regards security.
 *
 * The fact that you are presently reading this means that you have had
 * knowledge of the CeCILL license and that you accept its terms.
 */

/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Site\Navigation\Link\LinkInterface $link
 * @var array $data
 */
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');

$label = $data['label'] ?? null;
$searchConfigId = $data['advancedsearch_config_id'] ?? null;

$searchConfigs = $this->api()->search('search_configs')->getContent();
?>

<label><?php $translate('Type'); ?>
    <input type="text" value="<?php echo $escape($link->getName()); ?>" disabled="disabled">
</label>
<label><?php $translate('Label'); ?>
    <input type="text" data-name="label" value="<?php echo $escape($label); ?>">
</label>
<label>
    <?php echo $translate('Page'); ?>
    <select data-name="advancedsearch_config_id">
        <?php foreach ($searchConfigs as $searchConfig): ?>
            <?php $selected = $searchConfigId && $searchConfigId == $searchConfig->id(); ?>
            <option value="<?php echo $searchConfig->id(); ?>" <?php echo ($selected) ? 'selected="selected"' : ''; ?>>
                <?php echo $searchConfig->name(); ?>
            </option>
        <?php endforeach; ?>
    </select>
</label>
