<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \AdvancedSearch\Form\Admin\SearchSuggesterForm $form
 */

$plugins = $this->getHelperPluginManager();
$assetUrl = $plugins->get('assetUrl');
$translate = $plugins->get('translate');

$this->headLink()
    ->appendStylesheet($assetUrl('css/advanced-search-manager.css', 'AdvancedSearch'));
$this->headScript()
    ->appendFile($assetUrl('js/advanced-search-manager.js', 'AdvancedSearch'), 'text/javascript', ['defer' => 'defer']);

$this->htmlElement('body')->appendAttribute('class', 'search-admin search-suggester resource add');

$form->prepare();
?>

<?= $this->pageTitle($translate('Add suggester'), 1, $translate('Search manager')) ?>

<?= $this->form()->openTag($form) ?>
<div id="page-actions">
    <button type="submit" class="button"><?= $translate('Add') ?></button>
</div>
<?= $this->formCollection($form, false) ?>
<?php $this->trigger('view.add.form.after'); ?>
<?= $this->form()->closeTag() ?>
<?php $this->trigger('view.add.after'); ?>

