<?php

/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \AdvancedSearch\Form\Admin\SearchSuggesterForm $form
 */

$translate = $this->plugin('translate');
$form->prepare();
?>

<?= $this->pageTitle($translate('Add suggester')) ?>

<?= $this->form()->openTag($form) ?>
<div id="page-actions">
    <button type="submit"><?= $translate('Add') ?></button>
</div>
<?= $this->formCollection($form, false) ?>
<?php $this->trigger('view.add.form.after'); ?>
<?= $this->form()->closeTag() ?>
<?php $this->trigger('view.add.after'); ?>

<?php if (!$form->getOption('is_internal')): ?>
    <?= $translate('Only the internal adapter can have settings for now. For external suggesters, use the direct url in the search config.') ?>
<?php endif; ?>
