<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \AdvancedSearch\Api\Representation\SearchEngineRepresentation $resource
 * @var string $resourceLabel
 * @var array $listJobStatusesByIds
 * @var string $partialPath
 */

?>

<?= $this->searchSuggesterConfirm($this->resource, $this->resourceLabel, false, $listJobStatusesByIds) ?>
<?php if (isset($this->partialPath)): ?>
    <?= $this->partial($this->partialPath) ?>
<?php endif; ?>
