<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \AdvancedSearch\Api\Representation\SearchSuggesterRepresentation $resource
 * @var \Omeka\Form\ConfirmForm $form
 * @var string $wrapSidebar
 * @var string $resourceLabel
 * @var int $totalJobs
 */

$translate = $this->plugin('translate');

$resourceTypes = $resource->engine()->setting('resource_types', []);

$this->form->setAttribute('action', $resource->url('index'));
$this->form->setButtonLabel($translate('Confirm reindex'));
?>

<?php if ($this->wrapSidebar): ?>
<div id="index" class="sidebar">
    <?= $this->hyperlink('', '#', ['class' => 'sidebar-close o-icon-close', 'title' => $translate('Close')]) ?>
<?php endif; ?>
<?php if (count($resourceTypes)): ?>
    <div id="sidebar-confirm">
        <h3><?= sprintf($translate('Reindex "%s"'), $resource->name()) ?></h3>
        <p><?= $translate('Are you sure you would like to reindex this suggester?') ?></p>
        <p>
        <?= $translate('All the suggestions will be cleared first, so the search will be unavailable for a while (instant for mode "full" by sql, some minutes or some hours else).') ?>
        <?= $translate('You may redirect the users to a clone of the current suggester temporary.') ?>
        </p>
        <p>
            <?= $translate('Process of indexation') ?>
            <br/>
            <br/>
            <input form="<?= $form->getName() ?>" type="radio" name="process_mode" id="process_mode" value="sql"/><?= $translate('Direct sql (in particular mode "full")') ?>
            </br/>
            <input form="<?= $form->getName() ?>" type="radio" name="process_mode" id="process_mode" value="orm" checked="checked"/><?= $translate('Orm (slower but more precise index, required for old database, or small memory)') ?>
        </p>
        <p>
        <?php if ($totalJobs): ?>
            <?= sprintf($translate('%d running indexings.'), $totalJobs) ?><br />
            <input form="<?= $form->getName() ?>" name="force" type="checkbox" /><?= $translate('Force indexing') ?><br />
        <?php else: ?>
            <?= $translate('No running indexing: process can be launched.') ?>
        <?php endif; ?>
        </p>
        <p>
            <input form="<?= $form->getName() ?>" name="foreground" type="checkbox" /><?= $translate('Index in foreground') ?><br />
        </p>
        <?= $this->form($form) ?>
    </div>
<?php else: ?>
    <?= $translate('This index has no resource type to index.') ?>
<?php endif; ?>
<?php if ($this->wrapSidebar): ?>
</div>
<?php endif; ?>
