<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var string $name
 * @var string $value
 * @var string $label
 * @var int $count
 * @var bool $active
 * @var string $url
 * @var array $options
 * @var \Laminas\View\Helper\EscapeHtml $escapeHtml
 * @var \Laminas\View\Helper\EscapeHtmlAttr $escapeHtmlAttr
 * @var \Laminas\View\Helper\TranslatorAwareTrait $translate
 * @var \AdvancedSearch\View\Helper\FacetLabel $facetLabel
 *
 * @deprecated Use facet-links instead.
 */

$displayCount = !empty($options['display_count']);
?>

<span class="<?= $active ? 'active' : 'inactive' ?>">
    <a href="<?= $escapeHtmlAttr($url) ?>">
        <span>
            <?= $escapeHtml($label) ?>
            <?php if ($displayCount): ?>
            <span class="count">(<?= $count ?>)</span>
            <?php endif; ?>
        </span>
    </a>
</span>
