<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var string $name
 * @var array $facetValues With value, count, active, label and url when needed.
 * @var array $options Facets options.
 */

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');
$escape = $plugins->get('escapeHtml');
$escapeAttr = $plugins->get('escapeHtmlAttr');

$isFacetModeDirect = ($options['mode'] ?? '') === 'link';
$displayCount = !empty($options['display_count']);
?>

<select name="facet[<?= $name ?>][]" multiple="multiple" class="search-facet-items chosen-select" data-placeholder="<?= $translate('Select below…') ?>">
    <?php foreach ($facetValues as $facetValue): ?>
    <option value="<?= $escapeAttr($facetValue['value']) ?>"<?= $isFacetModeDirect ? ' data-url="' . $escapeAttr($facetValue['url']) . '"' : '' ?><?= $facetValue['active'] ? ' selected="selected"' : '' ?>>
        <?= $escape($facetValue['value']) ?><?php if ($displayCount): ?> (<span class="count"><?= $facetValue['count'] ?>)<?php endif; ?>
    </option>
    <?php endforeach; ?>
</select>
