<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var string $name
 * @var array $facetValues With value, count, active, label and url when needed.
 * @var array $options
 */

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$escapeAttr = $plugins->get('escapeHtmlAttr');

$isFacetModeDirect = ($options['mode'] ?? '') === 'link';
$displayCount = !empty($options['display_count']);
?>

<ul class="search-facet-items">
    <?php foreach ($facetValues as $facetValue):
        $escapedValue = $escapeAttr($facetValue['value']);
        $escapedId = $name . '[]' . $escapedValue;
        $label = $displayCount
            ? sprintf('%s (<span class="count">%d</span>)', $escape($facetValue['label']),  $facetValue['count'])
            : $escape($facetValue['label']);
    ?>
    <li class="search-facet-item">
        <input type="checkbox" name="facet[<?= $name ?>][]" id="<?= $escapedId ?>" value="<?= $escapedValue ?>"<?= $isFacetModeDirect ? ' data-url="' . $escapeAttr($facetValue['url']) . '"' : '' ?><?= $facetValue['active'] ? ' checked="checked"' : '' ?>/>
        <label for="<?= $escapedId ?>"><?= $label ?></label>
    </li>
    <?php endforeach; ?>
</ul>
