<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var string $name
 * @var array $facetValues With value, count, active, label and url when needed, and is_from and is_to.
 * @var array $options Facets options.
 * @var string|null $from
 * @var string|null $to
 * @var int $total Total resources matching range.
 */

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');
$escapeAttr = $plugins->get('escapeHtmlAttr');

$isFacetModeDirect = ($options['mode'] ?? '') === 'link';
$displayCount = !empty($options['display_count']);
?>

<div class="facet-select-range">
    <span><?= $translate('Between') ?></span>
    <select name="facet[<?= $name ?>][from]" class="search-facet-items chosen-select" data-placeholder="<?= $translate('Select below…') ?>">
        <option value=""></option>
        <?php foreach ($facetValues as $facetValue): ?>
        <option value="<?= $escapeAttr($facetValue['value']) ?>"<?= $isFacetModeDirect ? ' data-url="' . $escapeAttr($facetValue['url_from']) . '"' : '' ?><?= $facetValue['is_from'] ? ' selected="selected"' : '' ?>>
            <?= $escape($facetValue['value']) ?><?php if ($displayCount): ?> (<span class="count"><?= $facetValue['count'] ?></span>)<?php endif; ?>
        </option>
        <?php endforeach; ?>
    </select>
    <span><?= $translate('and') ?></span>
    <select name="facet[<?= $name ?>][to]" class="search-facet-items chosen-select" data-placeholder="<?= $translate('Select below…') ?>">
        <option value=""></option>
        <?php foreach ($facetValues as $facetValue): ?>
        <option value="<?= $escapeAttr($facetValue['value']) ?>"<?= $isFacetModeDirect ? ' data-url="' . $escapeAttr($facetValue['url_to']) . '"' : '' ?><?= $facetValue['is_to'] ? ' selected="selected"' : '' ?>>
            <?= $escape($facetValue['value']) ?><?php if ($displayCount): ?> (<span class="count"><?= $facetValue['count'] ?></span>)<?php endif; ?>
        </option>
        <?php endforeach; ?>
    </select>
</div>
