<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var string $name
 * @var string $value
 * @var string $label
 * @var int $count
 * @var bool $active
 * @var string $url
 * @var string|int|null $key
 * @var array $options
 * @var \Laminas\View\Helper\EscapeHtml $escapeHtml
 * @var \Laminas\View\Helper\EscapeHtmlAttr $escapeHtmlAttr
 * @var \Laminas\View\Helper\TranslatorAwareTrait $translate
 * @var \AdvancedSearch\View\Helper\FacetLabel $facetLabel
 */

// Warning: when inactive, don't return anything, in particular don't return any space,
// else it should be managed in facets.phtml.

if (!$active) return;

$texts = [
    'from' => '%1$s: from %2$s', // @translate
    'to' => '%1$s: to %2$s', // @translate
];
$text = $texts[$key] ?? '%1$s: %2$s'; // @translate

$replace = [
    '{url}' => $escapeHtmlAttr($url),
    '{facet_field}' => $escapeHtmlAttr($name),
    '{facet_value}' => $escapeHtmlAttr($value),
    '{facet_label}' => $escapeHtml(sprintf($text, $translate($facetLabel($name)), $label)),
];
?>

<?= str_replace(array_keys($replace), array_values($replace),
    '<a class="facet-active" href="{url}" data-facet-name="facet[{facet_field}][]" data-facet-value="{facet_value}">{facet_label}</a>') ?>
