<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var string $name
 * @var string $value
 * @var string $label
 * @var int $count
 * @var bool $active
 * @var string $url
 * @var \Laminas\View\Helper\EscapeHtml $escapeHtml
 * @var \Laminas\View\Helper\EscapeHtmlAttr $escapeHtmlAttr
 * @var \Laminas\View\Helper\TranslatorAwareTrait $translate
 * @var \Search\View\Helper\FacetLabel $facetLabel
 */
?>

<span class="<?= $active ? 'active' : 'inactive' ?>">
    <a href="<?= $escapeHtmlAttr($url) ?>"><?= $escapeHtml($label) ?></a>
    (<span class="count"><?= $count ?></span>)
</span>
