<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation|null $site
 * @var \AdvancedSearch\Api\Representation\SearchConfigRepresentation $searchConfig
 * @var \AdvancedSearch\Query $query
 * @var \AdvancedSearch\Response $response
 *
 * Options:
 * @var ?\Omeka\Api\Representation\ItemSetRepresentation $itemSet
 */

if (!isset($response)) return;

$searchFacets = $searchConfig->subSetting('facet', 'facets');
if (!count($searchFacets)) return;

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');

$facets = $response->getFacetCounts();
$activeFacets = $response->getActiveFacets();

// Don't display facet groups without facet elements.
$facets = array_filter($facets);

$isFacetModeButton = $searchConfig->subSetting('facet', 'mode') !== 'link';
$displayFacetButton = $isFacetModeButton && !empty($facets);
$displayActive = (bool) $searchConfig->subSetting('facet', 'display_active', true);
$displaySubmit = $displayFacetButton ? $searchConfig->subSetting('facet', 'display_submit', 'above') : 'none';
$labelSubmit = $displaySubmit ? $searchConfig->subSetting('facet', 'label_submit', $translate('Apply facets')) : null;
$displayReset = $searchConfig->subSetting('facet', 'display_reset', 'above');
$labelReset = $displayReset ? $searchConfig->subSetting('facet', 'label_reset', $translate('Reset facets')) : null;

$facetActives = $plugins->get('facetActives');
$facetElements = $plugins->get('facetElements');

// TODO Remove item sets facets early when item set redirects to search.
// Don't display facets for item sets when browsing an item set.
if (!empty($itemSet)) {
    unset($facets['item_set_id']);
    unset($activeFacets['item_set_id']);
}

// The only common option is the facet mode (button or direct link).
$options = ['mode' => $isFacetModeButton ? 'button' : 'link'];
?>

<div class="search-facets-content">

    <?php if ($facetsLabel = $searchConfig->subSetting('facet', 'label', $translate('Facets'))): ?>
    <h3><?= $escape($facetsLabel) ?></h3>
    <?php endif; ?>

    <?php if ($displayActive && count($activeFacets)): ?>
    <h4><?= $translate('Active facets') ?></h4>
    <?= $facetActives(null, $activeFacets, $options) ?>
    <?php endif; ?>

    <form id="form-facets">

        <?php if ($displayFacetButton): ?>
        <?= $this->hiddenInputsFromFilteredQuery(null, ['facet', 'page', 'limit', 'offset', 'per_page']) ?>
        <?php endif; ?>

        <?php $displayButtonReset = $displayReset === 'above' || $displayReset === 'both'; ?>
        <?php $displayButtonSubmit = $displayFacetButton && ($displaySubmit === 'above' || $displaySubmit === 'both'); ?>
        <?php if ($displayButtonReset || $displayButtonSubmit): ?>
        <div class="apply-facets apply-facets-top">
            <?php if ($displayButtonSubmit): ?>
            <button id="apply-facets" type="submit"><?= $labelSubmit ?></button>
            <?php endif; ?>
            <?php if ($displayButtonReset): ?>
            <button id="reset-facets" type="reset"><?= $labelReset ?></button>
            <?php endif; ?>
        </div>
        <?php endif; ?>

        <?php if (empty($facets) && empty($activeFacets)): ?>
        <p><?= $translate('No facets.') ?></p>
        <?php else: ?>
        <ul class="search-facets-list">
            <?php foreach ($facets as $name => $facetValues): ?>
            <?php $facetOptions = $searchFacets[$name] + $options; ?>
            <li class="search-facet">
                <h4><?= $escape($translate($facetOptions['label'] ?? $name)) ?></h4>
                <?= $facetElements($name, $facetValues, $facetOptions) ?>
            </li>
            <?php endforeach; ?>
        </ul>
        <?php endif; ?>

        <?php $displayButtonReset = $displayReset === 'below' || $displayReset === 'both'; ?>
        <?php $displayButtonSubmit = $displayFacetButton && ($displaySubmit === 'below' || $displaySubmit === 'both'); ?>
        <?php if ($displayButtonReset || $displayButtonSubmit): ?>
        <div class="apply-facets apply-facets-bottom">
            <?php if ($displayButtonSubmit): ?>
            <button id="apply-facets" type="submit"><?= $labelSubmit ?></button>
            <?php endif; ?>
            <?php if ($displayButtonReset): ?>
            <button id="reset-facets" type="reset"><?= $labelReset ?></button>
            <?php endif; ?>
        </div>
        <?php endif; ?>

    </form>

</div>
