<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var string $name
 * @var string $value
 * @var string $label
 * @var int $count
 * @var bool $active
 * @var string $url
 * @var \Laminas\View\Helper\EscapeHtml $escapeHtml
 */

$escapedValue = $escapeHtml($value);
$escapedId = $name . '[]' . $escapedValue;
?>

<input type="checkbox" name="<?= $name ?>[]" id="<?= $escapedId ?>" value="<?= $escapedValue ?>" data-url="<?= $url ?>" <?php if ($active) echo ' checked="checked"'; ?>/>
<label for="<?= $escapedId ?>"><?= $escapeHtml($label) ?> (<span class="count"><?= $count ?></span>)</label>
