<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var string $name
 * @var string $value
 * @var string $label
 * @var int $count
 * @var bool $active
 * @var string $url
 * @var array $options
 * @var \Laminas\View\Helper\EscapeHtml $escapeHtml
 * @var \Laminas\View\Helper\EscapeHtmlAttr $escapeHtmlAttr
 * @var \Laminas\View\Helper\TranslatorAwareTrait $translate
 * @var \AdvancedSearch\View\Helper\FacetLabel $facetLabel
 *
 * @deprecated Use facet-checkboxes instead.
 */

$escapedValue = $escapeHtmlAttr($value);
$escapedId = $name . '[]' . $escapedValue;
$displayCount = !empty($options['display_count']);
?>

<input type="checkbox" name="facet[<?= $name ?>][]" id="<?= $escapedId ?>" value="<?= $escapedValue ?>" data-url="<?= $escapeHtmlAttr($url) ?>" <?php if ($active) echo ' checked="checked"'; ?>/>
<label for="<?= $escapedId ?>"><span><?= $escapeHtml($label) ?><?php if ($displayCount): ?> <span class="count">(<?= $count ?>)</span><?php endif; ?></span></span></label>
