<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var string $name
 * @var array $facetValues With value, count, active, label and url when needed.
 * @var array $options
 * @var array|null $tree For item sets tree or thesaurus. Don't contain data from item sets not in the site.
 */

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$escapeAttr = $plugins->get('escapeHtmlAttr');

$isFacetModeDirect = ($options['mode'] ?? '') === 'link';
$displayCount = !empty($options['display_count']);

$isTree = is_array($tree);
?>

<ul class="facet-items">
    <?php foreach ($facetValues as $facetValue):
        $escapedValue = $escapeAttr($facetValue['value']);
        $escapedId = $name . '[]' . $escapedValue;
        $label = $displayCount
            ? sprintf('<span>%s <span class="count">(%d)</span></span>', $escape($facetValue['label']),  $facetValue['count'])
            : $escape($facetValue['label']);
        $treeVal = $isTree ? $tree[$facetValue['value']] ?? null : null;
        $treeValAttrs = $treeVal ? sprintf(' data-value="%s" data-parent="%s" data-level="%s"', $treeVal['id'], $treeVal['parent'], $treeVal['level']) : '';
    ?>
    <li class="facet-item <?= $facetValue['active'] ? 'active' : 'inactive' ?>"<?= $treeValAttrs ?>>
        <input type="checkbox" name="<?= "facet[$name][]" ?>" id="<?= $escapedId ?>" value="<?= $escapedValue ?>"<?= $isFacetModeDirect ? ' data-url="' . $escapeAttr($facetValue['url']) . '"' : '' ?><?= $facetValue['active'] ? ' checked="checked"' : '' ?>/>
        <label for="<?= $escapedId ?>"><?= $label ?></label>
    </li>
    <?php endforeach; ?>
</ul>
