<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \AdvancedSearch\Api\Representation\SearchConfigRepresentation $searchConfig
 * @var \AdvancedSearch\Api\Representation\SearchConfigRepresentation $searchPage Alias of $searchConfig
 * @var \AdvancedSearch\Query $query
 * @var \AdvancedSearch\Response $response
 *
 * Options:
 * @var ?\Omeka\Api\Representation\ItemSetRepresentation $itemSet
 */

if (!isset($response) || empty($searchConfig->subSetting('facet', 'facets'))) return;

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');

$facets = $response->getFacetCounts();
$activeFacets = $response->getActiveFacets();

// Don't display facet groups without facet elements.
$facets = array_filter($facets);

$displayActive = (bool) $searchConfig->subSetting('facet', 'display_active', true);

$isFacetModeButton = $searchConfig->subSetting('facet', 'mode') !== 'link';
$displayFacetButton = $isFacetModeButton && !empty($facets);
$displaySubmit = $displayFacetButton ? $searchConfig->subSetting('facet', 'display_submit', 'above') : 'none';
$displayReset = $searchConfig->subSetting('facet', 'display_reset', 'above');

$facetActives = $plugins->get('facetActives');
$facetLabel = $plugins->get('facetLabel');
// Facet checkbox can be used in any case anyway, the js checks it.
$facetElements = $isFacetModeButton ? $plugins->get('facetCheckboxes') : $plugins->get('facetLinks');
$facetSelect = $plugins->get('facetSelect');
$facetSelectRange = $plugins->get('facetSelectRange');
$facetElementsTree = $isFacetModeButton ? $plugins->get('facetCheckboxesTree') : $plugins->get('facetLinksTree');

// Don't display facets for item sets when browsing an item set.
if (!empty($itemSet)) {
    unset($facets['item_set_id']);
    unset($activeFacets['item_set_id']);
}

$options = $searchConfig->setting('facet', []);
?>

<aside class="search-facets">

    <?php if ($facetsLabel = $searchConfig->subSetting('facet', 'label', $translate('Facets'))): ?>
    <h3><?= $escape($facetsLabel) ?></h3>
    <?php endif; ?>

    <?php if ($displayActive && count($activeFacets)): ?>
    <h4><?= $translate('Active facets') ?></h4>
    <?= $facetActives(null, $activeFacets, $options) ?>
    <?php endif; ?>

    <form id="form-facets">

        <?php if ($displayFacetButton): ?>
        <?= $this->hiddenInputsFromFilteredQuery(null, ['facet', 'page', 'limit', 'offset', 'per_page']) ?>
        <?php endif; ?>

        <?php $r = ($displayReset === 'above' || $displayReset === 'both'); ?>
        <?php $s = ($displayFacetButton && ($displaySubmit === 'above' || $displaySubmit === 'both')); ?>
        <?php if ($r || $s): ?>
        <div class="apply-facets apply-facets-top">
            <?php if ($s): ?>
            <button id="apply-facets" type="submit"><?= $translate('Apply facets') ?></button>
            <?php endif ?>
            <?php if ($r): ?>
            <button id="reset-facets" type="reset"><?= $translate('Reset facets') ?></button>
            <?php endif ?>
        </div>
        <?php endif; ?>

        <?php if (empty($facets) && empty($activeFacets)): ?>
        <p><?= $translate('No facets.') ?></p>
        <?php else: ?>
        <ul class="search-facets-list">
            <?php foreach ($facets as $name => $facetValues): ?>
            <?php $facetType = empty($options['facets'][$name]['type']) ? 'Checkbox' : $options['facets'][$name]['type']; ?>
            <li class="search-facet">
                <h4><?= $translate($facetLabel($name)) ?></h4>
                <?php if ($facetType === 'Select'): ?>
                <?= $facetSelect($name, $facetValues, $options) ?>
                <?php elseif ($facetType === 'SelectRange'): ?>
                <?= $facetSelectRange($name, $facetValues, $options) ?>
                <?php elseif ($facetType === 'Tree'): ?>
                <?= $facetElementsTree($name, $facetValues, $options) ?>
                <?php else: ?>
                <?= $facetElements($name, $facetValues, $options) ?>
                <?php endif; ?>
            </li>
            <?php endforeach; ?>
        </ul>
        <?php endif; ?>

        <?php $r = ($displayReset === 'below' || $displayReset === 'both'); ?>
        <?php $s = ($displayFacetButton && ($displaySubmit === 'below' || $displaySubmit === 'both')); ?>
        <?php if ($r || $s): ?>
        <div class="apply-facets apply-facets-bottom">
            <?php if ($s): ?>
            <button id="apply-facets" type="submit"><?= $translate('Apply facets') ?></button>
            <?php endif ?>
            <?php if ($r): ?>
            <button id="reset-facets" type="reset" form="form-facets"><?= $translate('Reset facets') ?></button>
            <?php endif ?>
        </div>
        <?php endif; ?>

    </form>

</aside>
