<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \AdvancedSearch\Api\Representation\SearchConfigRepresentation $searchPage
 * @var \AdvancedSearch\Query $query
 * @var \AdvancedSearch\Response $response
 * @var string $title
 * @var string $resourceName
 */

$resources = $response->getResources($resourceName);
// A check is done: when page is not first, the resources may be empty even with results.
if (!$resources) return;

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$assetUrl = $plugins->get('assetUrl');
$translate = $plugins->get('translate');
$hyperlink = $plugins->get('hyperlink');
$thumbnailHelper = $plugins->get('thumbnail');

$setting = $plugins->get($site ? 'siteSetting' : 'setting');

$filterLocale = (bool) $setting('filter_locale_values');
$siteLang = $plugins->get('lang')();
$lang = $filterLocale ? $siteLang : null;
$langValue = $filterLocale ? [$siteLang, ''] : null;

$headingTerm = $setting('browse_heading_property_term');
$bodyTerm = $setting('browse_body_property_term');

$gridListMode = $searchPage ? $searchPage->subSetting('display', 'grid_list_mode', 'auto') : 'auto';

$defaultThumbnail = '<img src="' . $assetUrl('thumbnails/default.png', 'Omeka', true) . '" title="' . $translate('No media') . '"/>';
?>

<?php if ($title): ?>
<h3><?= $escape($title) ?></h3>
<?php endif; ?>
<ul class="resource-list search-results-list<?= $gridListMode === 'list_only' ? ' list' : ($gridListMode === 'grid_only' ? ' grid' : '') ?>">
    <?php /** @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource */
    foreach ($resources as $resource):
        $resourceType = $resource->resourceName();
        $media = $resource->primaryMedia();
        $thumbnail = $media ? $thumbnailHelper($media, 'medium') : $defaultThumbnail;
        if ($headingTerm) $heading = $resource->value($headingTerm, ['lang' => $langValue]);
        if (empty($heading)) $heading = $resource->displayTitle($translate('[Untitled]'), $lang);
        if ($bodyTerm) $body = $resource->value($bodyTerm, ['lang' => $langValue]);
        if (empty($body)) $body = $resource->displayDescription(null, $lang);
    ?>

    <li class="resource <?= $resourceType ?>">
        <div class="resource-thumbnail">
            <?= $hyperlink->raw($thumbnail, $resource->url(), ['class' => 'resource-link']) ?>
        </div>
        <div class="resource-metadata">
            <h4><?= $resource->link($heading) ?></h4>
            <div class="description">
                <?= $escape($body) ?>
            </div>
        </div>
    </li>

    <?php endforeach; ?>
</ul>
