<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Search\Form\AdvancedForm $form
 */

// Scripts are loaded via an event on view.layout and can be set in in search-form-advanced-header.phtml.

$formCollection = $this->plugin('formCollection');
$formElement = $this->plugin('formElement');
$formHelper = $this->plugin('form');

$params = $this->params()->fromQuery() ?: [];
$form
    ->setData($params)
    ->prepare();
?>

<?= $formHelper->openTag($form) ?>
<div id="advanced-search-form-wrapper">
    <div id="advanced-search-form">
        <?= $this->formText($form->get('q')) ?>
        <?php if ($form->has('itemSet')): ?>
        <?= $formCollection($form->get('itemSet'), false) ?>
        <?php endif; ?>
        <?php if ($form->has('resourceClass')): ?>
        <?= $formCollection($form->get('resourceClass'), false) ?>
        <?php endif; ?>
        <?php if ($form->has('resourceTemplate')): ?>
        <?= $formCollection($form->get('resourceTemplate'), false) ?>
        <?php endif; ?>
        <div>
            <?php /** @var Zend\Form\Element\Collection $filters */ ?>
           <?php if ($form->has('text')): ?>
           <?php $textFieldset = $form->get('text'); ?>
            <?php if ($textFieldset->has('filters')): ?>
            <?php $filters = $textFieldset->get('filters'); ?>
            <div class="filters">
                <?php foreach ($filters->getFieldsets() as $fieldset): ?>
                    <?= $formCollection($fieldset, true) ?>
                <?php endforeach; ?>
                <?= $formCollection()->renderTemplate($filters) ?>
                <?php /*
                <button type="button" class="advanced-add-filter"><i class="fa fa-plus"></i></button>
                */ ?>
            </div>
            <?php endif; ?>
            <?php endif; ?>
        </div>
        <input type="submit" value="OK"/>
    </div>
</div>
<?= $formElement($form->get('csrf')) ?>
<?= $formHelper->closeTag() ?>
