<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \AdvancedSearch\Api\Representation\SearchConfigRepresentation $searchPage
 */

// Add headers (css or scripts) to be included for the form.
// The form itself is managed by search-form-main.

// The form can be used independantly of the search page, but they share the same css/js.

// Remove code to avoid to load the same files multiple times in your theme.

$assetUrl = $this->plugin('assetUrl');

if ($searchPage->subSetting('autosuggest', 'suggester')
    || $searchPage->subSetting('autosuggest', 'url')
) {
    $this->headScript()
        ->appendFile($assetUrl('vendor/jquery-autocomplete/jquery.autocomplete.min.js', 'AdvancedSearch'), 'text/javascript', ['defer' => 'defer']);
}

$this->headLink()
    ->appendStylesheet($assetUrl('vendor/chosen-js/chosen.min.css', 'Omeka'))
    ->appendStylesheet($assetUrl('css/search.css', 'AdvancedSearch'));
$this->headScript()
    ->appendFile($assetUrl('vendor/chosen-js/chosen.jquery.min.js', 'Omeka'), 'text/javascript', ['defer' => 'defer'])
    ->appendFile($assetUrl('js/search.js', 'AdvancedSearch'), 'text/javascript', ['defer' => 'defer']);
