<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Search\Form\AdvancedForm $form
 */

// Scripts are loaded via an event on view.layout and can be set in in search-form-advanced-header.phtml.

$params = $this->params()->fromQuery() ?: [];
$form
    ->setData($params)
    ->prepare();
?>

<div id="advanced-search-form-wrapper">
    <div id="advanced-search-form">
        <?= $this->form($form) ?>
    </div>
</div>
