<?php
/*
 * Copyright BibLibre, 2016
 * Copyright Daniel Berthereau, 2017-2023
 *
 * This software is governed by the CeCILL license under French law and abiding
 * by the rules of distribution of free software.  You can use, modify and/ or
 * redistribute the software under the terms of the CeCILL license as circulated
 * by CEA, CNRS and INRIA at the following URL "http://www.cecill.info".
 *
 * As a counterpart to the access to the source code and rights to copy, modify
 * and redistribute granted by the license, users are provided only with a
 * limited warranty and the software's author, the holder of the economic
 * rights, and the successive licensors have only limited liability.
 *
 * In this respect, the user's attention is drawn to the risks associated with
 * loading, using, modifying and/or developing or reproducing the software by
 * the user in light of its specific status of free software, that may mean that
 * it is complicated to manipulate, and that also therefore means that it is
 * reserved for developers and experienced professionals having in-depth
 * computer knowledge. Users are therefore encouraged to load and test the
 * software's suitability as regards their requirements in conditions enabling
 * the security of their systems and/or data to be ensured and, more generally,
 * to use and operate it in the same conditions as regards security.
 *
 * The fact that you are presently reading this means that you have had
 * knowledge of the CeCILL license and that you accept its terms.
 */

/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \AdvancedSearch\Api\Representation\SearchConfigRepresentation $searchConfig
 * @var \AdvancedSearch\Query $query
 * @var \AdvancedSearch\Response $response
 *
 * For block layout:
 * @var string $heading Used in the block layout template.
 * @var bool $skipFormAction Remove action of the form, so it uses current page.
 */

$plugins = $this->getHelperPluginManager();
$api = $plugins->get('api');
$partial = $plugins->get('partial');
$escape = $plugins->get('escapeHtml');
$assetUrl = $plugins->get('assetUrl');
$translate = $plugins->get('translate');
$hyperlink = $plugins->get('hyperlink');
$translatePlural = $plugins->get('translatePlural');

$breadcrumbs = $plugins->has('breadcrumbs') ? $plugins->get('breadcrumbs') : null;

$vars = $this->vars();

$setting = $plugins->get(isset($site) ? 'siteSetting' : 'setting');

$filterLocale = (bool) $setting('filter_locale_values');
$lang = $this->lang();
$langTitle = $filterLocale ? $lang : null;
$langValue = $filterLocale ? [$lang, ''] : null;

// Used in case of a redirect of item-set/show to search, when used like item/browse.
$itemSetId = $this->params()->fromRoute('item-set-id');
// TODO Use site item set ?
/** @var \Omeka\Api\Representation\ItemSetRepresentation $itemSet */
$itemSet = $itemSetId ? $api->searchOne('item_sets', ['id' => $itemSetId])->getContent() : null;

$isPartial = $skipFormAction = !empty($skipFormAction);

$documentCount = isset($response) ? $response->getTotalResults() : 0;
if ($documentCount):
    $itemSetsCount = $response->getResourceTotalResults('item_sets');
    $itemsCount = $response->getResourceTotalResults('items');
    $displayParts = $searchConfig->setting('display', []);
    $displayPartsHeader = array_filter($displayParts, function ($v) { return in_array($v, ['header', 'both']); });
    $displayPartsFooter = array_filter($displayParts, function ($v) { return in_array($v, ['footer', 'both']); });
else:
    $itemSetsCount = 0;
    $itemsCount = 0;
    $displayPartsHeader = [];
    $displayPartsFooter = [];
endif;

$this->headLink()
    ->appendStylesheet($assetUrl('css/search.css', 'AdvancedSearch'));
$this->headScript()
    ->appendFile($assetUrl('js/search.js', 'AdvancedSearch'), 'text/javascript', ['defer' => 'defer']);
?>

<?php if (empty($isPartial)): ?>
<?php if ($breadcrumbs): ?>
    <?= $breadcrumbs() ?>
<?php else: ?>
<nav id="breadcrumb" class="breadcrumbs">
    <ul>
        <?php if (isset($site)): ?>
        <li><?= $hyperlink($translate('Home'), $site->siteUrl()) ?></li>
        <?php endif; ?>
        <?php if ($itemSet): ?>
        <li><?= $translate('Collections') ?></li>
        <li><span><?= isset($site) ? $itemSet->siteUrl($site->slug()) : $itemSet->adminUrl() ?></span></li>
        <?php endif; ?>
        <li><span><?= $escape($translate('Search')) ?></span></li>
    </ul>
</nav>
<?php endif; ?>

<div id="search-page">
<?php endif; ?>

<?php if ($itemSet): ?>

    <?php
    $vars->offsetSet('itemSet', $itemSet);
    $vars->offsetSet('resourceType', 'item_sets'); // TODO Check if really needed.
    $this->htmlElement('body')->appendAttribute('class', 'search-page item-set resource browse');
    ?>
    <?= $this->pageTitle($itemSet->displayTitle(null, $langTitle), 2) ?>
    <h3><?= $translate('Item set') ?></h3>
    <div class="metadata">
        <?= $itemSet->displayValues() ?>
    </div>
    <div class="item-set-items">
        <h3><?= $translate('Items') ?></h3>
    </div>

<?php else: ?>

    <?php $this->htmlElement('body')->appendAttribute('class', 'search-page resource browse'); ?>
    <?= $this->pageTitle($translate('Search'), 2) ?>

<?php endif; ?>

<?= $searchConfig->renderForm(['template' => null, 'skip_form_action' => $skipFormAction]) ?>

<?php if (isset($response)): ?>

<div class="search-results-wrapper">
    <div class="search-results">

        <?php if ($documentCount): ?>

        <?php if ($displayPartsHeader): ?>
        <div class="search-results-part search-results-header">
            <?= $partial('search/results-header-footer', [
                'site' => $site,
                'searchConfig' => $searchConfig,
                // Kept for compatibility with old themes.
                'searchPage' => $searchConfig,
                'query' => $query,
                'response' => $response,
                'itemSet' => $itemSet,
                'resultPart' => 'header',
                'documentCount' => $documentCount,
            ]) ?>
        </div>
        <?php endif; ?>

        <div class="search-results-part search-results-list">
            <?php if ($itemSetsCount): ?>
            <?= $partial('search/resource-list', [
                'site' => $site,
                'searchConfig' => $searchConfig,
                'searchPage' => $searchConfig,
                'query' => $query,
                'response' => $response,
                'title' => sprintf($translatePlural('%s item set', '%s item sets', $itemSetsCount), $itemSetsCount),
                'resourceName' => 'item_sets',
            ]) ?>
            <?php endif; ?>

            <?php if ($itemsCount): ?>
            <?= $partial('search/resource-list', [
                'site' => $site,
                'searchConfig' => $searchConfig,
                'searchPage' => $searchConfig,
                'query' => $query,
                'response' => $response,
                'title' => sprintf($translatePlural('%s item', '%s items', $itemsCount), $itemsCount),
                'resourceName' => 'items',
            ]) ?>
            <?php endif; ?>
        </div>

        <?php if ($displayPartsFooter): ?>
        <div class="search-results-part search-results-footer">
            <?= $partial('search/results-header-footer', [
                'site' => $site,
                'searchConfig' => $searchConfig,
                'searchPage' => $searchConfig,
                'query' => $query,
                'response' => $response,
                'itemSet' => $itemSet,
                'resultPart' => 'footer',
                'documentCount' => $documentCount,
            ]) ?>
        </div>
        <?php endif; ?>

        <?php else: ?>

            <div class="noresults">
                <?php if (empty($query) && !$itemSet): ?>
                <?= $translate('Fill a query and get results.') ?>
                <?php elseif (empty($query) && $itemSet): ?>
                <?= $translate('This item set has no items.') ?>
                <?php else: ?>
                <?php if (in_array($searchConfig->subSetting('display', 'search_filters', 'header'), ['header', 'both'])): ?>
                <div class="search-results-part search-results-header">
                    <?= $this->searchingFilters($searchConfig, $query, ['template' => 'common/search-filters-links']) ?>
                </div>
                <?php endif; ?>
                <?= $translate('Your query returned no results') ?>
                <?php endif; ?>
            </div>

        <?php endif; ?>

    </div>

    <?= $partial('search/facets', [
        'site' => $site,
        'searchConfig' => $searchConfig,
        'searchPage' => $searchConfig,
        'query' => $query,
        'response' => $response,
        'itemSet' => $itemSet,
    ]) ?>
</div>

<?php else: ?>

<div class="search-results-wrapper">
    <div class="search-results">
        <div class="noresults"><?= $translate('An error occured and your query returned no results.') ?></div>
    </div>
</div>

<?php endif; ?>

<?php if (empty($isPartial)): ?>
</div>
<?php endif; ?>
