<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \AdvancedSearch\Api\Representation\SearchConfigRepresentation $searchConfig
 * @var \Laminas\Form\Form $form
 */

// Add headers (css or scripts) to be included for the form.
// The form itself is managed by search-form-main.

// The form can be used independantly of the search page, but they share the same css/js.

// Remove code to avoid to load the same files multiple times in your theme.

$plugins = $this->getHelperPluginManager();
$status = $plugins->get('status');
$assetUrl = $plugins->get('assetUrl');
$headLink = $plugins->get('headLink');
$headScript = $plugins->get('headScript');

if ($searchConfig->subSetting('autosuggest', 'suggester')
    || $searchConfig->subSetting('autosuggest', 'url')
) {
    $headScript
        ->appendFile($assetUrl('vendor/jquery-autocomplete/jquery.autocomplete.min.js', 'AdvancedSearch'), 'text/javascript', ['defer' => 'defer']);
}

if (!$status->isAdminRequest()) {
    $headLink
        ->prependStylesheet($assetUrl('vendor/chosen-js/chosen.css', 'Omeka'));
    $headScript
        ->appendFile($assetUrl('vendor/chosen-js/chosen.jquery.min.js', 'Omeka'), 'text/javascript', ['defer' => 'defer']);
}

$headLink
    ->appendStylesheet($assetUrl('css/search.css', 'AdvancedSearch'));
$headScript
    ->appendFile($assetUrl('js/search.js', 'AdvancedSearch'), 'text/javascript', ['defer' => 'defer']);
