<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Zend\Form\Form $form
 */

// This quick form displays only the first field (the main one) and the required or hidden elements.

$params = $this->params()->fromQuery() ?: [];
$form
    ->setData($params)
    ->prepare();

$main = null;
foreach ($form->getElements() as $element):
    if ($element instanceof \Zend\Form\Element\Csrf || $element instanceof \Zend\Form\Element\Hidden || $element instanceof \Zend\Form\Element\Submit):
        continue;
    endif;
    if ($main):
        if (!$element->getOption('required')):
            $form->remove($element->getName());
        endif;
    else:
        $main = $element;
    endif;
endforeach;

foreach ($form->getFieldsets() as $fieldset):
    $form->remove($fieldset->getName());
endforeach;
?>

<?= $this->form($form) ?>
