<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 */

// Add headers (css or scripts) to be included for the form.
// The form itself is managed by search-form-advanced.

$assetUrl = $this->plugin('assetUrl');

$this->headLink()
    ->appendStylesheet($this->assetUrl('vendor/chosen-js/chosen.min.css', 'Omeka'));
$this->headScript()
    ->appendFile($assetUrl('vendor/chosen-js/chosen.jquery.min.js', 'Omeka'), 'text/javascript', ['defer' => 'defer']);
