<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \AdvancedSearch\Form\MainSearchForm $form
 * @var \AdvancedSearch\Api\Representation\SearchConfigRepresentation $searchConfig
 * @var \AdvancedSearch\Api\Representation\SearchConfigRepresentation $searchPage Alias of $searchConfig
 */

// Scripts are loaded via an event on view.layout and can be managed in search-form-main-header.phtml.

$params = $this->params()->fromQuery() ?: [];
$form
    ->setData($params)
    ->prepare();
?>

<div id="advanced-search-form-wrapper">
    <div id="advanced-search-form">
        <?= $this->form($form) ?>
    </div>
</div>
