<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Laminas\Form\Form $form
 * @var \AdvancedSearch\Api\Representation\SearchConfigRepresentation $searchConfig
 * @var \AdvancedSearch\Api\Representation\SearchConfigRepresentation $searchPage Alias of $searchConfig
 */

$params = $this->params()->fromQuery() ?: [];
$form
    ->setData($params)
    ->prepare();
?>

<?= $this->form($form) ?>
