<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \AdvancedSearch\Query $query
 * @var \Laminas\Form\Element\Select $select
 * @var array $options
 * @var bool $asUrl
 */

if (count($options) <= 1) return;
?>

<div class="search-sort<?= $asUrl ? ' as-url' : '' ?>">
    <?= $select->getlabel() === null ? '' : $this->formLabel($select) ?>
    <?= $this->formSelect($select) ?>
</div>
