<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \AdvancedSearch\Query $query
 * @var \Laminas\Form\Element\Select $select
 * @var array $params
 */

if (count($select->getValueOptions()) <= 1) return;
?>

<div class="search-sort<?= empty($params['as_url']) ? '' : ' as-url' ?>">
    <?= $select->getlabel() ? $this->formLabel($select) : '' ?>
    <div class="select-parent">
        <?= $this->formSelect($select) ?>
    </div>
</div>
