<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \AdvancedSearch\Query $query
 * @var array $sortOptions
 * @var ?\Laminas\Form\Element\Select $sortSelect
 * @var bool $asSortUrls
 */

if (empty($sortSelect)) return;
?>

<div class="search-sort<?= $asSortUrls ? ' search-sort-urls' : '' ?>">
    <?= $this->formLabel($sortSelect) ?>
    <?= $this->formSelect($sortSelect) ?>
</div>
