<?php
/*
 * Copyright BibLibre, 2016-2017
 * Copyright Daniel Berthereau, 2017-2026
 *
 * This software is governed by the CeCILL license under French law and abiding
 * by the rules of distribution of free software.  You can use, modify and/ or
 * redistribute the software under the terms of the CeCILL license as circulated
 * by CEA, CNRS and INRIA at the following URL "http://www.cecill.info".
 *
 * As a counterpart to the access to the source code and rights to copy, modify
 * and redistribute granted by the license, users are provided only with a
 * limited warranty and the software's author, the holder of the economic
 * rights, and the successive licensors have only limited liability.
 *
 * In this respect, the user's attention is drawn to the risks associated with
 * loading, using, modifying and/or developing or reproducing the software by
 * the user in light of its specific status of free software, that may mean that
 * it is complicated to manipulate, and that also therefore means that it is
 * reserved for developers and experienced professionals having in-depth
 * computer knowledge. Users are therefore encouraged to load and test the
 * software's suitability as regards their requirements in conditions enabling
 * the security of their systems and/or data to be ensured and, more generally,
 * to use and operate it in the same conditions as regards security.
 *
 * The fact that you are presently reading this means that you have had
 * knowledge of the CeCILL license and that you accept its terms.
 */

/**
 * @var Laminas\View\Renderer\PhpRenderer|Laminas\Form\View\HelperTrait $this
 * @var \AdvancedSearch\Api\Representation\SearchConfigRepresentation $searchConfig
 * @var \AdvancedSearch\Form\Admin\SearchConfigConfigureForm $form
 */

$plugins = $this->getHelperPluginManager();
$assetUrl = $plugins->get('assetUrl');
$translate = $plugins->get('translate');

$this->headLink()
    ->appendStylesheet($assetUrl('css/advanced-search-manager.css', 'AdvancedSearch'));
$this->headScript()
    ->appendFile($assetUrl('js/advanced-search-manager.js', 'AdvancedSearch'), 'text/javascript', ['defer' => 'defer']);

$this->htmlElement('body')->appendAttribute('class', 'search-admin search-config resource edit configure');

$searchEngine = $searchConfig->searchEngine();
$engineAdapter = $searchEngine ? $searchEngine->engineAdapter() : null;
if (empty($engineAdapter)) {
    return;
}

$form->prepare();

$navTab = [];
foreach ($form->getFieldsets() as $fieldset) {
    $navTab[$fieldset->getName()] = $translate($fieldset->getLabel());
}
?>

<?= $this->pageTitle(sprintf($translate('Search page "%1$s" (%2$s)'), $searchConfig->name(), $searchConfig->slug()), 1, $translate('Search manager')) ?>

<div id="page-actions">
    <button form="search-config-configure-form" class="button"><?= $translate('Save') ?></button>
</div>

<nav class="section-nav">
    <?= $this->navigation('Laminas\Navigation\AdvancedSearch\Config')->menu() ?>
</nav>

<?= $this->form()->openTag($form) ?>

<nav class="section-nav sub-section-nav ">
    <?= $this->sectionNav($navTab, null, $searchConfig) ?>
</nav>

<?php $next = -1; ?>
<?php foreach ($form->getFieldsets() as $name => $fieldset): ?>
<?= $this->formCollection($fieldset->setAttributes(['id' => $name, 'class' => 'section' . (++$next ? '' : ' active') , 'aria-labelledby' => $name . '-label'])) ?>
<?php endforeach; ?>

<?php foreach ($form->getElements() as $element): ?>
<?= $this->formElement($element) ?>
<?php endforeach; ?>

<?= $this->form()->closeTag() ?>
