<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \AdvancedSearch\Api\Representation\SearchConfigRepresentation $searchConfig
 * @var \AdvancedSearch\Form\Admin\SearchConfigConfigureForm $form
 */

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');
$assetUrl = $plugins->get('assetUrl');

$this->headLink()
    ->appendStylesheet($assetUrl('css/advanced-search-manager.css', 'AdvancedSearch'));
$this->headScript()
    ->appendFile($assetUrl('js/advanced-search-manager.js', 'AdvancedSearch'), 'text/javascript', ['defer' => 'defer']);

$this->htmlElement('body')->appendAttribute('class', 'search-admin search-config resource edit');

if (empty($form)) {
    echo $this->pageTitle(sprintf($translate('Search page "%1$s" (%2$s)'), $searchConfig->name(), $searchConfig->slug()), 1, $translate('Search manager'));
    return;
}

$form->prepare();

$navTab = [];
foreach ($form->getFieldsets() as $fieldset) {
    $navTab[$fieldset->getName()] = $translate($fieldset->getLabel());
}
?>

<?= $this->pageTitle(sprintf($translate('Search page "%1$s" (%2$s)'), $searchConfig->name(), $searchConfig->slug()), 1, $translate('Search manager')) ?>

<?= $this->form()->openTag($form) ?>

<div id="page-actions">
    <button type="submit" class="button"><?= $translate('Save') ?></button>
</div>

<nav class="section-nav sub-section-nav">
    <?= $this->sectionNav($navTab, null, $searchConfig) ?>
</nav>

<?php $next = -1; ?>
<?php foreach ($form->getFieldsets() as $name => $fieldset): ?>
<?= $this->formCollection($fieldset->setAttributes(['id' => $name, 'class' => 'section' . (++$next ? '' : ' active'), 'aria-labelledby' => $name . '-label'])) ?>
<?php endforeach; ?>

<?php foreach ($form->getElements() as $element): ?>
<?= $this->formElement($element) ?>
<?php endforeach; ?>

<?php $this->trigger('view.edit.form.after'); ?>
<?= $this->form()->closeTag() ?>
<?php $this->trigger('view.edit.after'); ?>
